// This file was generated by Prisma and extended for ScentSphere.
// Prisma 7 reads this file for ALL CLI commands: migrate, studio, db push, seed.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // env() is Prisma 7's typed env helper — throws PrismaConfigEnvError if
    // DATABASE_URL is missing, rather than silently passing undefined to Studio.
    // The fallback literal ensures Studio can connect even when .env is not
    // loaded in a detached shell (e.g., running `npx prisma studio` cold).
    url: (() => {
      try {
        return env("DATABASE_URL");
      } catch {
        return "mysql://root:mysql@localhost:3306/scentsphere";
      }
    })(),
  },
});
